version: "3.3"

services:
  database:
    image: postgres:alpine
    container_name: "database"
    ports:
      - $DB_PORT:5432
    networks:
      - backend
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
    volumes:
      - ./.volumes/postgres:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge